import { FaqItem, FaqList } from '@/components/faq'

export function FaqSection() {
  return (
    <FaqList>
      <FaqItem question='What are PRTs?'>
        <p>
          Product Revenue Tokens (PRTs) are ERC20 tokens which, when staked,
          enable the holder to receive a share of an Index Product’s revenue.
          PRTs can be earned via presale participation and other activities
          related to the respective product.
        </p>
        <p>
          PRTs allow users to share the product’s revenue after it is launched.
          For example, if you own 10% of all PRTs for hyETH, you will be
          entitled to 10% of all future revenue generated by hyETH.
        </p>
        <p>
          PRT holders must stake their PRTs to receive their share of product
          fees. Unstaked PRTs may be freely traded on secondary markets.
        </p>
      </FaqItem>
      <FaqItem question='How do I stake my PRTs?'>
        <p>
          In order to stake your PRTs and receive your share of the product’s
          revenue, you must visit the PRT Staking Interface on the Index Coop
          App. Locate the product for which you want to stake your PRTs and
          click ‘Manage’. From here, you should be able to see both the ‘Total
          PRTs Staked’ and ‘Your Staked PRTs’.
        </p>
        <p>
          Input the amount of PRTs you would like to stake (or select ‘Max’ to
          stake all the PRTs in your current wallet) and submit the transaction
          by clicking the ‘Stake’ button. Confirm the transaction in your
          wallet, and after the transaction is completed you should see an
          updated total reflected in the ‘Your Staked PRTs’ field.
        </p>
      </FaqItem>
      <FaqItem question='How do I unstake my PRTs?'>
        <p>
          Similarly to staking, unstaking is handled through the ‘Manage’ modal
          in the PRT Staking Interface. Locate the product from which you want
          to unstake your PRTs and click ‘Manage’. From there, select the
          ‘Unstake’ tab.
        </p>
        <p>
          Input the amount of PRTs you would like to unstake (or select ‘Max’ to
          unstake all the PRTs) and submit the transaction by clicking the
          ‘Unstake’ button. Confirm the transaction, and after it is completed,
          you should receive the PRTs in your wallet.
        </p>
      </FaqItem>
      <FaqItem question='How high are the rewards?'>
        <p>
          PRTs are claims on fees generated by hyETH. For example, suppose hyETH
          has a TVL of $100m and a user holds 500 PRTs. This entitles them to 5%
          of the revenue generated by hyETH. hyETH has a streaming fee of 0.95%
          per year. So, $100m in TVL would generate $950,000 per year in
          revenue. The user holding 500 staked PRTs would earn $47,500 annually.{' '}
          <strong className='font-bold'>
            It is worth noting though, that product TVL can be unpredictable,
            and revenue is not guaranteed for perpetuity because Index Coop can
            deprecate unsuccessful products following an $INDEX governance vote.
          </strong>
        </p>
        <p>
          Another note is that the revenue will be distributed proportionally
          amongst staked PRTs. For example, if a user holds 500 PRTs but only
          5,000 PRTs are currently staked (instead of a 100% staking
          participation rate), then the user will earn 10% of the fees instead
          of 5%.
        </p>
        <p>
          Additionally, it is possible PRTs in secondary markets may trade at a
          multiple of annual revenue or a significant discount to annual
          revenue. It’s too early to say how much these assets could be worth.
        </p>
      </FaqItem>
      <FaqItem question='How often are rewards distributed?'>
        <p>
          Tokens typically emit their revenue at the end of the month. All users
          who have their PRTs staked at this point in time will be able to
          receive their proportionate share of the product’s revenue.
        </p>
        <p>
          hyETH revenue will accrue to the staking pool on a monthly basis, at
          which point PRT stakers can claim their proportional share of rewards.
          PRT stakers are not obligated to claim rewards on a monthly basis;
          rewards can accrue over the course of several months and be claimed at
          the staker’s convenience.
        </p>
      </FaqItem>
      <FaqItem question='How do I claim my rewards?'>
        <p>
          Claiming is handled through the PRT Staking Interface. Locate the
          product for which you want to claim rewards and click ‘Manage’. From
          there, select the ‘Claim’ tab. In this tab, you can view both your
          currently claimable and lifetime rewards, and claim your rewards.
        </p>
      </FaqItem>
      <FaqItem question='Who is able to stake?'>
        <p>
          PRT holders who are not{' '}
          <a
            href='https://indexcoop.com/tokens-restricted-for-restricted-persons'
            target='_blank'
            className='underline'
          >
            Restricted Persons
          </a>{' '}
          are eligible for staking their PRTs and receiving a share of product
          revenue.
        </p>
      </FaqItem>
      <FaqItem question='Have the PRT contracts been audited?'>
        <p>
          Yes, the{' '}
          <a
            href='https://etherscan.io/address/0x99f6539df9840592a862ab916ddc3258a1d7a773'
            target='_blank'
            className='underline'
          >
            PRT Token
          </a>
          ,{' '}
          <a
            href='https://etherscan.io/address/0xBe03026716a4D5E0992F22A3e6494b4F2809a9C6'
            target='_blank'
            className='underline'
          >
            PRT Staking Pool
          </a>
          , and{' '}
          <a
            href='https://etherscan.io/address/0x43c3ef32e52f17777789c71002ef4a887df90613'
            target='_blank'
            className='underline'
          >
            PRT Fee Split Extension
          </a>{' '}
          contracts have all been audited by a leading independent security
          researcher,{' '}
          <a href='https://x.com/IAm0x52' target='_blank' className='underline'>
            0x52
          </a>
          . The public audit report can be found{' '}
          <a
            href='https://github.com/IndexCoop/audits/blob/main/audits/IndexPRTAuditReport.md'
            target='_blank'
            className='underline'
          >
            here
          </a>
          .
        </p>
      </FaqItem>
    </FaqList>
  )
}
