import './globals.css'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import { Providers } from './providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <Providers>{children}</Providers>
      </body>
      <Script src='https://tag.safary.io/stag.js' async />
    </html>
  )
}
