export const FlashMintLeveragedExtendedAbi = [
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: 'quickRouter', type: 'address' },
          { internalType: 'address', name: 'sushiRouter', type: 'address' },
          { internalType: 'address', name: 'uniV3Router', type: 'address' },
          { internalType: 'address', name: 'uniV3Quoter', type: 'address' },
          {
            internalType: 'address',
            name: 'curveAddressProvider',
            type: 'address',
          },
          { internalType: 'address', name: 'curveCalculator', type: 'address' },
          { internalType: 'address', name: 'weth', type: 'address' },
        ],
        internalType: 'struct DEXAdapter.Addresses',
        name: '_addresses',
        type: 'tuple',
      },
      {
        internalType: 'contract IController',
        name: '_setController',
        type: 'address',
      },
      {
        internalType: 'contract IDebtIssuanceModule',
        name: '_debtIssuanceModule',
        type: 'address',
      },
      {
        internalType: 'contract IAaveLeverageModule',
        name: '_aaveLeverageModule',
        type: 'address',
      },
      { internalType: 'address', name: '_aaveV3Pool', type: 'address' },
      { internalType: 'address', name: '_vault', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: '_recipient',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'contract ISetToken',
        name: '_setToken',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: '_inputToken',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_amountInputToken',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_amountSetIssued',
        type: 'uint256',
      },
    ],
    name: 'FlashMint',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: '_recipient',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'contract ISetToken',
        name: '_setToken',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: '_outputToken',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_amountSetRedeemed',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_amountOutputToken',
        type: 'uint256',
      },
    ],
    name: 'FlashRedeem',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'previousOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    inputs: [],
    name: 'LENDING_POOL',
    outputs: [{ internalType: 'contract IPool', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'ROUNDING_ERROR_MARGIN',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'aaveLeverageModule',
    outputs: [
      {
        internalType: 'contract IAaveLeverageModule',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'addresses',
    outputs: [
      { internalType: 'address', name: 'quickRouter', type: 'address' },
      { internalType: 'address', name: 'sushiRouter', type: 'address' },
      { internalType: 'address', name: 'uniV3Router', type: 'address' },
      { internalType: 'address', name: 'uniV3Quoter', type: 'address' },
      {
        internalType: 'address',
        name: 'curveAddressProvider',
        type: 'address',
      },
      { internalType: 'address', name: 'curveCalculator', type: 'address' },
      { internalType: 'address', name: 'weth', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract ISetToken',
        name: '_setToken',
        type: 'address',
      },
    ],
    name: 'approveSetToken',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'contract IERC20', name: '_token', type: 'address' },
    ],
    name: 'approveToken',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'contract IERC20[]', name: '_tokens', type: 'address[]' },
    ],
    name: 'approveTokens',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'balancerV2Vault',
    outputs: [{ internalType: 'contract IVault', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'debtIssuanceModule',
    outputs: [
      {
        internalType: 'contract IDebtIssuanceModule',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract ISetToken',
        name: '_setToken',
        type: 'address',
      },
      { internalType: 'uint256', name: '_setAmount', type: 'uint256' },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataDebtForCollateral',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataInputToken',
        type: 'tuple',
      },
    ],
    name: 'getIssueExactSet',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract ISetToken',
        name: '_setToken',
        type: 'address',
      },
      { internalType: 'uint256', name: '_setAmount', type: 'uint256' },
      { internalType: 'bool', name: '_isIssuance', type: 'bool' },
    ],
    name: 'getLeveragedTokenData',
    outputs: [
      {
        components: [
          {
            internalType: 'address',
            name: 'collateralAToken',
            type: 'address',
          },
          { internalType: 'address', name: 'collateralToken', type: 'address' },
          {
            internalType: 'uint256',
            name: 'collateralAmount',
            type: 'uint256',
          },
          { internalType: 'address', name: 'debtToken', type: 'address' },
          { internalType: 'uint256', name: 'debtAmount', type: 'uint256' },
        ],
        internalType: 'struct FlashMintLeveraged.LeveragedTokenData',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract ISetToken',
        name: '_setToken',
        type: 'address',
      },
      { internalType: 'uint256', name: '_setAmount', type: 'uint256' },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataCollateralForDebt',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataOutputToken',
        type: 'tuple',
      },
    ],
    name: 'getRedeemExactSet',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract ISetToken',
        name: '_setToken',
        type: 'address',
      },
      { internalType: 'uint256', name: '_setAmount', type: 'uint256' },
      { internalType: 'address', name: '_inputToken', type: 'address' },
      {
        internalType: 'uint256',
        name: '_maxAmountInputToken',
        type: 'uint256',
      },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataDebtForCollateral',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataInputToken',
        type: 'tuple',
      },
    ],
    name: 'issueExactSetFromERC20',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract ISetToken',
        name: '_setToken',
        type: 'address',
      },
      { internalType: 'uint256', name: '_setAmount', type: 'uint256' },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataDebtForCollateral',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataInputToken',
        type: 'tuple',
      },
    ],
    name: 'issueExactSetFromETH',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract ISetToken',
        name: '_setToken',
        type: 'address',
      },
      { internalType: 'uint256', name: '_minSetAmount', type: 'uint256' },
      { internalType: 'address', name: '_inputToken', type: 'address' },
      { internalType: 'uint256', name: '_inputTokenAmount', type: 'uint256' },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataDebtForCollateral',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataInputTokenForCollateral',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataInputTokenForETH',
        type: 'tuple',
      },
      {
        internalType: 'uint256',
        name: '_priceEstimateInflator',
        type: 'uint256',
      },
      { internalType: 'uint256', name: '_maxDust', type: 'uint256' },
    ],
    name: 'issueSetFromExactERC20',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract ISetToken',
        name: '_setToken',
        type: 'address',
      },
      { internalType: 'uint256', name: '_minSetAmount', type: 'uint256' },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataDebtForCollateral',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataInputTokenForCollateral',
        type: 'tuple',
      },
      {
        internalType: 'uint256',
        name: '_priceEstimateInflator',
        type: 'uint256',
      },
      { internalType: 'uint256', name: '_maxDust', type: 'uint256' },
    ],
    name: 'issueSetFromExactETH',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'maxGasRebate',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'maxIterations',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'contract IERC20[]', name: 'tokens', type: 'address[]' },
      { internalType: 'uint256[]', name: 'amounts', type: 'uint256[]' },
      { internalType: 'uint256[]', name: 'feeAmounts', type: 'uint256[]' },
      { internalType: 'bytes', name: 'userData', type: 'bytes' },
    ],
    name: 'receiveFlashLoan',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract ISetToken',
        name: '_setToken',
        type: 'address',
      },
      { internalType: 'uint256', name: '_setAmount', type: 'uint256' },
      { internalType: 'address', name: '_outputToken', type: 'address' },
      {
        internalType: 'uint256',
        name: '_minAmountOutputToken',
        type: 'uint256',
      },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataCollateralForDebt',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataOutputToken',
        type: 'tuple',
      },
    ],
    name: 'redeemExactSetForERC20',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract ISetToken',
        name: '_setToken',
        type: 'address',
      },
      { internalType: 'uint256', name: '_setAmount', type: 'uint256' },
      {
        internalType: 'uint256',
        name: '_minAmountOutputToken',
        type: 'uint256',
      },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataCollateralForDebt',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataOutputToken',
        type: 'tuple',
      },
    ],
    name: 'redeemExactSetForETH',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract ISetToken',
        name: '_setToken',
        type: 'address',
      },
      { internalType: 'uint256', name: '_maxSetAmount', type: 'uint256' },
      { internalType: 'address', name: '_outputToken', type: 'address' },
      { internalType: 'uint256', name: '_outputTokenAmount', type: 'uint256' },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataCollateralForDebt',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataCollateralForOutputToken',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataDebtForCollateral',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataOutputTokenForCollateral',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataOutputTokenForETH',
        type: 'tuple',
      },
      {
        internalType: 'uint256',
        name: '_priceEstimateInflator',
        type: 'uint256',
      },
      { internalType: 'uint256', name: '_maxDust', type: 'uint256' },
    ],
    name: 'redeemSetForExactERC20',
    outputs: [{ internalType: 'uint256', name: 'setAmount', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract ISetToken',
        name: '_setToken',
        type: 'address',
      },
      { internalType: 'uint256', name: '_maxSetAmount', type: 'uint256' },
      { internalType: 'uint256', name: '_outputTokenAmount', type: 'uint256' },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataCollateralForDebt',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataCollateralForOutputToken',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataDebtForCollateral',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'address[]', name: 'path', type: 'address[]' },
          { internalType: 'uint24[]', name: 'fees', type: 'uint24[]' },
          { internalType: 'address', name: 'pool', type: 'address' },
          {
            internalType: 'enum DEXAdapter.Exchange',
            name: 'exchange',
            type: 'uint8',
          },
        ],
        internalType: 'struct DEXAdapter.SwapData',
        name: '_swapDataOutputTokenForCollateral',
        type: 'tuple',
      },
      {
        internalType: 'uint256',
        name: '_priceEstimateInflator',
        type: 'uint256',
      },
      { internalType: 'uint256', name: '_maxDust', type: 'uint256' },
    ],
    name: 'redeemSetForExactETH',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'setController',
    outputs: [
      { internalType: 'contract IController', name: '', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_maxGasRebate', type: 'uint256' },
    ],
    name: 'setMaxGasRebate',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_maxIterations', type: 'uint256' },
    ],
    name: 'setMaxIterations',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { stateMutability: 'payable', type: 'receive' },
] as const
