name: Unit Tests
env:
  NEXT_PUBLIC_ALCHEMY_ID: ${{ secrets.NEXT_PUBLIC_ALCHEMY_ID }}

# Triggers the workflow on push or pull request events
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Copy .env vars
        run: cp .env.default .env.local
      - name: Set env
        run: echo "NEXT_PUBLIC_ALCHEMY_ID=$(echo $NEXT_PUBLIC_ALCHEMY_ID | cut -c 1-6)" >> $NEXT_PUBLIC_ALCHEMY_ID
      - name: Install
        run: npm ci
      - name: Run unit tests
        run: npm run hardhat & npm run test
